### ISSUE TITLE
Bug in `set_chunks` which leads to the wrong chunks being used:

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#103]
This still seems to be an issue after merging #72:
```
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        data_group = sv.create_group('data')
        data_group.create_dataset('bar', data=np.arange(4))

with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('1') as sv:
        data_group = sv['data']
        data_group.create_dataset('props/1/bar', data=np.arange(0, 4, 2))
```
which complains about
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/set_chunks_dict_bug.py", line 15, in <module>
    data_group.create_dataset('props/1/bar', data=np.arange(0, 4, 2))
  File "/opt/python/python-3.7/lib64/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/api.py", line 170, in stage_version
    timestamp=timestamp)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 96, in commit_version
    raise NotImplementedError("Specifying chunk size with dict data")
NotImplementedError: Specifying chunk size with dict data
```

_Originally posted by @ArvidJB in https://github.com/deshaw/versioned-hdf5/pull/72#issuecomment-659119626_

**Comment by asmeurer** [comment]
Ah, I missed this one. Fixed at https://github.com/deshaw/versioned-hdf5/pull/107. We don't have enough test coverage for closing the file and reopening it, which takes some different code paths because otherwise it reuses some stuff in memory.
