### ISSUE TITLE
Issues with fancy index and slicing

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#133]
I ran into an issue with code that does the following:
```
with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('0') as sv:
        a = np.full((5, 5, 5), 0)
        sv.create_dataset('bar', data=a, chunks=(20, 20, 20))

with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('1') as sv:
        ds = sv['bar']
        ds.resize((8, 9, 10))
        print(ds[np.array([2, 5, 6, 7]), 1:9, 5:10])
```
which gave the following error
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/dense_reshape_fill.py", line 16, in <module>
    print(ds[np.array([2, 5, 6, 7]), 1:9, 5:10])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 563, in __getitem__
    arr[arr_idx.raw] = self.id.data_dict[c][index.raw]
ValueError: could not broadcast input array from shape (4,8,5) into shape (4,5,5)
```

**Comment by asmeurer** [comment]
Should be fixed by https://github.com/Quansight/ndindex/pull/80
