### ISSUE TITLE
Selecting with bool mask broken?

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#201]
This seems to no longer work as of the latest release:
```
from __future__ import absolute_import, division

from   versioned_hdf5           import VersionedHDF5File

import h5py
import numpy as np

with h5py.File('foo.h5', 'w') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('r0') as sv:
        sv.create_dataset('bar', data=[1, 2, 3], chunks=(2,))

with h5py.File('foo.h5', 'r+') as f:
    vf = VersionedHDF5File(f)
    with vf.stage_version('r1') as sv:
        mask = np.array([True, True, False], dtype='bool')
        b = sv['bar'][mask]
```
gives the following error
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/bool_mask.py", line 17, in <module>
    b = sv['bar'][mask]
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 1107, in __getitem__
    return self.dataset.__getitem__(index)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 644, in __getitem__
    return super().__getitem__(args)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python/python-3.7/std/lib64/python3.7/site-packages/h5py/_hl/dataset.py", line 573, in __getitem__
    self.id.read(mspace, fspace, arr, mtype, dxpl=self._dxpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 182, in h5py.h5d.DatasetID.read
  File "h5py/_proxy.pyx", line 130, in h5py._proxy.dset_rw
  File "h5py/_proxy.pyx", line 84, in h5py._proxy.H5PY_H5Dread
OSError: Can't read data (point selections not currently supported)
```
git bisect points to commit 198c6b9175a22afb61d63a52b27e6f045e8b1858.

**Comment by asmeurer** [comment]
I didn't realize that we were inadvertently supporting index types that aren't supported by HDF5 itself for virtual datasets. We can do a fallback, but this unfortunately means the optimization from https://github.com/deshaw/versioned-hdf5/pull/194 won't apply if the index is a mask.

**Comment by quarl** [comment]
Thanks for the fix.
Would it be faster if you convert the mask to indices and then use the fast code path?  I.e. if it's a mask then first convert to arange(len(N))[mask]?

Also, can you make a release?  Without the fix (whether this slow fix, or a fast fix), it's a breaking issue for us.

**Comment by asmeurer** [comment]
Ah yeah, it looks like integer arrays work too. That is a simpler fix and still keeps the fast path.

**Comment by asmeurer** [comment]
And yeah, I will cut the release as soon as tests pass in #203

**Comment by asmeurer** [comment]
I also opened an upstream issue about this in h5py https://github.com/h5py/h5py/issues/1936

**Comment by quarl** [comment]
Thanks!
