### ISSUE TITLE
delete_versions can corrupt files (PyInf#8559)

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#238]
With HDF5 files containing arbitrary length strings a call to `delete_versions` seems to lead to a corrupt file. However, this does only seem to manifest itself after running `h5repack` on the file.

Here is a reproducer:
```
import subprocess
import h5py
import numpy as np
from versioned_hdf5 import VersionedHDF5File, delete_versions

if __name__ == '__main__':
    lorem_ipsum = np.array("Lorem ipsum dolor sit amet, consectetur "
                           "adipiscing elit, sed do eiusmod tempor incididunt "
                           "ut labore et dolore magna aliqua.".split(' '), dtype='O')

    with h5py.File('/tmp/foo.h5', 'w') as f:
        vf = VersionedHDF5File(f)
        with vf.stage_version('r0') as sv:
            dt = h5py.string_dtype(encoding='ascii')
            sv.create_dataset('bar', data=lorem_ipsum, chunks=(100,), dtype=dt)
            sv.create_dataset('baz', data=[], chunks=(100,), dtype=np.dtype('int64'))

    for v in range(1, 11):
        with h5py.File('/tmp/foo.h5', 'r+') as f:
            vf = VersionedHDF5File(f)
            with vf.stage_version(f'r{v}') as sv:
                sv['baz'].resize((v,))
                sv['baz'][v - 1] = v - 1

    with h5py.File('/tmp/foo.h5', 'r+') as f:
        delete_versions(f, ['r2', 'r5'])

    p = subprocess.Popen(['h5repack', '/tmp/foo.h5', '/tmp/foo2.h5'])
    p.wait()

    for v in range(11, 12):
        with h5py.File('/tmp/foo2.h5', 'r+') as f:
            vf = VersionedHDF5File(f)
            with vf.stage_version(f'r{v}') as sv:
                sv['baz'].resize((v,))
                sv['baz'][v - 1] = v - 1
```
which leads to following error:
```
Traceback (most recent call last):
  File "/u/bessen/opensource/versioned-hdf5/replay_versions_string_bug.py", line 36, in <module>
    with vf.stage_version(f'r{v}') as sv:
  File "/opt/python/python-3.10/lib64/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/api.py", line 195, in stage_version
    group = create_version_group(self.f, version_name,
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 59, in create_version_group
    prev_group.visititems(_get)
  File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/h5py/_hl/group.py", line 636, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/h5py/_hl/group.py", line 635, in proxy
    return func(name, self[name])
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 53, in _get
    group[name] = item
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 100, in __setitem__
    self._add_to_data(name, obj)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 111, in _add_to_data
    wrapped_dataset = self._data[name] = DatasetWrapper(InMemoryDataset(obj.id, parent=self))
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 450, in __init__
    super().__init__(InMemoryDatasetID(bind.id), **kwargs)
  File "/u/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 1128, in __init__
    self.raw_data = g[raw_data_name]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/h5py/_hl/group.py", line 337, in __getitem__
    return dataset.Dataset(oid, readonly=(self.file.mode == 'r'))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/h5py/_hl/dataset.py", line 622, in __init__
    self._dcpl = self.id.get_create_plist()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 334, in h5py.h5d.DatasetID.get_create_plist
RuntimeError: Can't get creation plist (bad global heap collection signature)
```

**Comment by ArvidJB** [comment]
A couple more observations:
* `f['_version_data/bar/raw_data']` is not readable and seems to cause this error
* the reproducer can be simplified even more:
  * 'baz' is not necessary
  * just calling `delete_versions(f, [])` seems to be sufficient to reproduce this

**Comment by asmeurer** [comment]
Your script doesn't produce any errors for me. What version of h5repack are you using?

**Comment by peytondmurray** [comment]
If this is the same issue as #244 then I think this has been fixed by https://github.com/deshaw/versioned-hdf5/pull/248. Closing for now, please reopen if this issue still affects the latest version.

**Comment by ArvidJB** [comment]
We encountered this issue again, for a non-empty dataset:
```
import shutil
import subprocess
import tempfile

import h5py
import numpy as np
from   versioned_hdf5           import VersionedHDF5File
from   versioned_hdf5.replay    import delete_versions

if __name__ == '__main__':
    d = tempfile.mkdtemp()
    try:
        fn = d + '/data.h5'
        with h5py.File(fn, 'w') as f:
            vf = VersionedHDF5File(f)
            with vf.stage_version('r0') as sv:
                sv.create_dataset('a', data=np.arange(10).astype('S2').astype('O'),
                                  dtype=h5py.string_dtype(encoding='ascii'),
                                  chunks=(10000,), maxshape=(None,))
                sv.create_dataset('b', data=np.arange(10))

        for i in range(1, 21):
            with h5py.File(fn, 'r+') as f:
                vf = VersionedHDF5File(f)
                with vf.stage_version('r{}'.format(i)) as sv:
                    sv['a'] = np.arange(10).astype('S2').astype('O')
                    sv['b'] = np.arange(i, 10 + i)
            with h5py.File(fn, 'r+') as f:
                vf = VersionedHDF5File(f)
                versions = [v for v in vf._versions if v != '__first_version__']
                if len(versions) > 10:
                    sorted_versions = sorted(versions, key=lambda v: vf._versions[v].attrs['timestamp'])
                    delete_versions(f, sorted_versions[:-1])

            repacked_fn = tempfile.mktemp(dir=d)
            subprocess.run(['h5repack', str(fn), str(repacked_fn)])
            shutil.move(repacked_fn, fn)
    finally:
        shutil.rmtree(d)
```
gives the following error:
```
Traceback (most recent call last):
  File "/codemill/bessen/opensource/versioned-hdf5/version_retention_string_bug.py", line 25, in <module>
    with vf.stage_version('r{}'.format(i)) as sv:
  File "/opt/python/python-3.10/lib64/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/api.py", line 201, in stage_version
    group = create_version_group(self.f, version_name,
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 59, in create_version_group
    prev_group.visititems(_get)
  File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/h5py/_hl/group.py", line 664, in visititems
    return h5o.visit(self.id, proxy)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 355, in h5py.h5o.visit
  File "h5py/h5o.pyx", line 302, in h5py.h5o.cb_obj_simple
  File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/h5py/_hl/group.py", line 663, in proxy
    return func(name, self[name])
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 53, in _get
    group[name] = item
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 100, in __setitem__
    self._add_to_data(name, obj)
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 111, in _add_to_data
    wrapped_dataset = self._data[name] = DatasetWrapper(InMemoryDataset(obj.id, parent=self))
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 450, in __init__
    super().__init__(InMemoryDatasetID(bind.id), **kwargs)
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/wrappers.py", line 1128, in __init__
    self.raw_data = g[raw_data_name]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/h5py/_hl/group.py", line 366, in __getitem__
    return dataset.Dataset(oid, readonly=(self.file.mode == 'r'))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/usr/local/python/python-3.10/std/lib64/python3.10/site-packages/h5py/_hl/dataset.py", line 649, in __init__
    self._dcpl = self.id.get_create_plist()
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 382, in h5py.h5d.DatasetID.get_create_plist
RuntimeError: Unable to get dataset creation properties (address of object past end of allocation)
```
