### ISSUE TITLE
h5py 2.10 tests fail with AttributeError: module 'numpy' has no attribute 'typeDict'

### ISSUE THREAD

**Issue by asmeurer** [deshaw/versioned-hdf5#243]
```
============================= test session starts ==============================
platform linux -- Python 3.8.15, pytest-7.2.1, pluggy-1.0.0 -- /usr/share/miniconda/envs/test-environment/bin/python3.8
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/_pytest/terminal.py", line 720, in pytest_sessionstart
INTERNALERROR>     lines = self.config.hook.pytest_report_header(
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/_pytest/config/compat.py", line 67, in fixed_hook
INTERNALERROR>     return hook(**kw)
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_hooks.py", line 265, in __call__
INTERNALERROR>     return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/pluggy/_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/runner/work/versioned-hdf5/versioned-hdf5/conftest.py", line 2, in pytest_report_header
INTERNALERROR>     import h5py
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/h5py/__init__.py", line 46, in <module>
INTERNALERROR>     from ._conv import register_converters as _register_converters
INTERNALERROR>   File "h5py/_conv.pyx", line 1, in init h5py._conv
INTERNALERROR>   File "h5py/h5t.pyx", line 293, in init h5py.h5t
INTERNALERROR>   File "/usr/share/miniconda/envs/test-environment/lib/python3.8/site-packages/numpy/__init__.py", line 284, in __getattr__
INTERNALERROR>     raise AttributeError("module {!r} has no attribute "
INTERNALERROR> AttributeError: module 'numpy' has no attribute 'typeDict'
```

**Comment by asmeurer** [comment]
My guess is that we need to pin numpy for these CI builds.
