### ISSUE TITLE
Chunk reuse code failing on multi-dimensional array (PyInf#11487)

### ISSUE THREAD

**Issue by ArvidJB** [deshaw/versioned-hdf5#333]
Here's some code that seems to fail with the changes in https://github.com/deshaw/versioned-hdf5/commit/7662655467ec987e2efb28abde968b6a8cb7ad13:
```
import h5py
import numpy
import shutil
import tempfile
from   versioned_hdf5           import VersionedHDF5File

if __name__ == '__main__':
    # create temp dir path to be cleaned up on exit
    dir = tempfile.mkdtemp()
    path = f'{dir}/data.h5'
    try:
        rs = numpy.random.RandomState(0)
        dims = 3
        with h5py.File(path, 'w') as f:
            vf = VersionedHDF5File(f)
            with vf.stage_version('v0') as sv:
                for i in range(dims):
                    sv.create_dataset(f'axis{i}', dtype=numpy.dtype('int64'), shape=(0,),
                                      chunks=(10000,), maxshape=(None,))
                sv.create_dataset('value', dtype=numpy.dtype('int64'),
                                  shape=tuple([0 for _ in range(dims)]),
                                  chunks=tuple([20 for _ in range(dims)]),
                                  maxshape=tuple([None for _ in range(dims)]),
                                  fillvalue=0)
                sv.create_dataset('mask', dtype=numpy.dtype('int8'),
                                  shape=tuple([0 for _ in range(dims)]),
                                  chunks=tuple([20 for _ in range(dims)]),
                                  maxshape=tuple([None for _ in range(dims)]),
                                  fillvalue=2)
        for i in range(1, 101):
            with h5py.File(path, 'r+') as f:
                vf = VersionedHDF5File(f)
                with vf.stage_version(f'v{i}') as sv:
                    new_axes = tuple(numpy.unique(rs.randint(30, size=5))
                                     for _ in range(dims))
                    new_value = numpy.full(tuple(len(ax) for ax in new_axes), i)
                    new_mask = numpy.full(tuple(len(ax) for ax in new_axes), 0)

                    # figure out how existing axes map to new axes
                    new_indices = []
                    existing_indices = []
                    new_shape = []
                    for i in range(dims):
                        axis_ds = sv[f'axis{i}']
                        all_axis, indices = numpy.unique(numpy.concatenate([axis_ds[:], new_axes[i]]),
                                                         return_inverse=True)
                        existing_indices.append(tuple(indices[:len(axis_ds)]))
                        new_indices.append(tuple(indices[len(axis_ds):]))
                        axis_ds.resize((len(all_axis),))
                        axis_ds[:] = all_axis
                        new_shape.append(len(all_axis))

                    new_indices = tuple(new_indices)
                    existing_indices = tuple(existing_indices)
                    new_shape = tuple(new_shape)

                    # merge value
                    value_ds = sv['value']
                    all_data = numpy.full(new_shape, value_ds.fillvalue)
                    existing_data = value_ds[:]
                    all_data[numpy.ix_(*existing_indices)] = existing_data
                    all_data[numpy.ix_(*new_indices)] = new_value
                    value_ds.resize(new_shape)
                    value_ds[:] = all_data

                    # merge mask
                    mask_ds = sv['mask']
                    all_mask = numpy.full(new_shape, mask_ds.fillvalue)
                    existing_mask = mask_ds[:]
                    all_mask[numpy.ix_(*existing_indices)] = existing_mask
                    all_mask[numpy.ix_(*new_indices)] = new_mask
                    mask_ds.resize(new_shape)
                    mask_ds[:] = all_mask
    finally:
        shutil.rmtree(dir)
```
which fails for me with
```
/usr/local/bin/python3.11 /codemill/bessen/opensource/versioned-hdf5/append_insert.py 
Traceback (most recent call last):
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 306, in _verify_new_chunk_reuse
    assert_array_equal(reused_chunk, to_be_written)
  File "/usr/local/python/python-3.11/std/lib64/python3.11/site-packages/numpy/testing/_private/utils.py", line 985, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/opt/python/python-3.11/lib64/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/python-3.11/std/lib64/python3.11/site-packages/numpy/testing/_private/utils.py", line 778, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(shapes (20, 20, 20), (20, 20, 6) mismatch)
 x: array([[[0, 2, 2, ..., 2, 2, 2],
        [0, 2, 2, ..., 2, 2, 2],
        [2, 2, 2, ..., 2, 2, 2],...
 y: array([[[0, 2, 2, 2, 2, 0],
        [0, 2, 2, 2, 2, 2],
        [2, 2, 2, 2, 2, 2],...

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/codemill/bessen/opensource/versioned-hdf5/append_insert.py", line 33, in <module>
    with vf.stage_version(f'v{i}') as sv:
  File "/opt/python/python-3.11/lib64/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/api.py", line 307, in stage_version
    commit_version(
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/versions.py", line 162, in commit_version
    slices = write_dataset(
             ^^^^^^^^^^^^^^
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 194, in write_dataset
    _verify_new_chunk_reuse(
  File "/codemill/bessen/opensource/versioned-hdf5/versioned_hdf5/backend.py", line 308, in _verify_new_chunk_reuse
    raise ValueError(
ValueError: Hash b'\x80|\xebF\x95\xb4-\xaa\xc3\xdf\x95\x98\xd7\x94w\x8c\xc8|\xc2\xe3\x1e\xeet\xf9\xe0\xd1i\x18\xc6\x94\x7f\x95' of existing data chunk [[[0 2 2 ... 2 2 2]
  [0 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  ...
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  [0 2 2 ... 2 2 2]]

 [[2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  ...
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]]

 [[2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  ...
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]]

 ...

 [[2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  ...
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]]

 [[0 0 2 ... 2 2 2]
  [0 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  ...
  [2 2 2 ... 2 2 2]
  [2 0 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]]

 [[2 0 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]
  ...
  [2 2 2 ... 2 2 2]
  [2 0 2 ... 2 2 2]
  [2 2 2 ... 2 2 2]]] matches the hash of new data chunk [[[0 2 2 2 2 0]
  [0 2 2 2 2 2]
  [2 2 2 2 2 2]
  ...
  [2 2 2 2 2 0]
  [2 2 2 2 2 0]
  [0 2 2 2 2 2]]

 [[2 2 2 2 2 2]
  [2 2 2 2 2 2]
  [2 2 2 2 2 2]
  ...
  [2 2 2 2 2 2]
  [2 2 2 2 2 2]
  [2 2 2 2 2 2]]

 [[2 2 2 2 2 2]
  [2 2 2 2 2 2]
  [2 2 2 2 2 2]
  ...
  [2 2 2 0 0 2]
  [2 2 2 0 0 2]
  [2 2 2 2 2 2]]

 ...

 [[2 2 2 2 2 2]
  [2 2 2 2 2 2]
  [2 2 2 2 2 2]
  ...
  [2 2 2 0 0 2]
  [2 2 2 0 0 2]
  [2 2 2 2 2 2]]

 [[0 0 2 2 2 0]
  [0 2 2 2 2 2]
  [2 2 2 2 2 2]
  ...
  [2 2 2 2 2 2]
  [2 0 2 2 2 0]
  [2 2 2 2 2 2]]

 [[2 0 2 2 2 0]
  [2 2 2 2 2 2]
  [2 2 2 2 2 2]
  ...
  [2 2 2 2 2 2]
  [2 0 2 2 2 0]
  [2 2 2 2 2 2]]], but data does not.

Process finished with exit code 1
```

_Originally posted by @ArvidJB in https://github.com/deshaw/versioned-hdf5/issues/327#issuecomment-2150902625_

**Comment by ArvidJB** [comment]
I am confused by
```
def _verify_new_chunk_reuse(
    raw_data: np.ndarray,
    new_data: np.ndarray,
    data_hash: bytes,
    hashed_slice: Tuple,
    chunk_being_written: Tuple,
    slices_to_write: Optional[Dict[Slice, Tuple]] = None,
    data_to_write: Optional[Dict[Slice, np.ndarray]] = None,
):
```
because it does not match how it is called:
```
                    _verify_new_chunk_reuse(
                        raw_data=ds,                # h5py.Dataset, not np.ndarray
                        new_data=data,              # type is correct, but this should be the slice of data to write, not all of data, I think?
                        data_hash=data_hash,
                        hashed_slice=hashed_slice,  # Slice, not a Tuple
                        chunk_being_written=data_s, # np.ndarray, not a Dict/None
                        slices_to_write=slices_to_write,
                    )
```
